/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.1
 * Generated at: 2018-11-16 02:35:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/./common.jsp", Long.valueOf(1539851088295L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("    <link rel=\"icon\" href=\"./resource/img/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("    <title>Project in YonginUniversity</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core CSS -->\r\n");
      out.write("    <link href=\"./resource/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom styles for this template -->\r\n");
      out.write("    <link href=\"./resource/resource/css/pricing.css\" rel=\"stylesheet\">\r\n");
      out.write("\t <link href=\"./resource/css/navbar.css\" rel=\"stylesheet\">\r\n");
      out.write("\t  <link href=\"./resource/css/blog.css\" rel=\"stylesheet\">");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom styles for this template -->\r\n");
      out.write("    <link href=\"./resource/css/form-validation.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<script src=\"./resource/js/script.js\"></script>\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body class=\"bg-light\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"py-5 text-center\">\r\n");
      out.write("        <img class=\"d-block mx-auto mb-4\" src=\"./resource/img/LOGO.png\" alt=\"\" width=\"72\" height=\"72\">\r\n");
      out.write("        <h2>회원가입</h2>\r\n");
      out.write("        <p class=\"lead\">회원가입을하면 프로젝트 등록및 신청을 할 수 있습니다.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"col-md-12 order-md-1\">\r\n");
      out.write("          <h4 class=\"mb-3\">기본정보</h4>\r\n");
      out.write("          <form  action=\"Join\" method=\"post\" class=\"needs-validation\" novalidate >\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                <label for=\"Name\">이름</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"name\" placeholder=\"\" name=\"name\"required>\r\n");
      out.write("                <div class=\"invalid-feedback\">\r\n");
      out.write("                  이름을 입력해주세요\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\t\t\t      \r\n");
      out.write("              <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                <label for=\"number\">학번/교번</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"number\" placeholder=\"\" name=\"number\" onkeydown='return onlyNumber(event)' onkeyup='removeChar(event)'required>\r\n");
      out.write("                <div class=\"invalid-feedback\">\r\n");
      out.write("                  학번을 입력해주세요\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-6 mb-3\">\r\n");
      out.write("              <label for=\"username\">비밀번호</label>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <input type=\"password\" class=\"form-control\" id=\"password\" name=\"password\" required>\r\n");
      out.write("                <div class=\"invalid-feedback\" style=\"width: 100%;\">\r\n");
      out.write("                  비밀번호를 입력해주세요\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("             <div class=\"col-md-6 mb-3\">\r\n");
      out.write("              <label for=\"username_check\">비밀번호확인</label>\r\n");
      out.write("                <input type=\"password\" class=\"form-control\" id=\"password\" name=\"password_check\" required>\r\n");
      out.write("                <div class=\"invalid-feedback\" style=\"width: 100%;\">\r\n");
      out.write("                  비밀번호를 입력해주세요\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("             <div class=\"col-md-6 mb-3\">\r\n");
      out.write("              <label for=\"username\">학과</label>\r\n");
      out.write("             <select  class=\"custom-select d-block w-100\" id=\"major\" name=\"major\"required >\r\n");
      out.write("                  <option value=\"\">Choose...</option>\r\n");
      out.write("\t\r\n");
      out.write("                  <option value=\"computer\" selected=\"selected\">컴퓨터과학과</option>\r\n");
      out.write("\t\t\t\t  <option value=\"Biology\">생명과학과</option>\r\n");
      out.write("\t\t\t\t  <option value=\"Environment\">환경학과</option>\r\n");
      out.write("\t\t\t\t  <option value=\"Logistics\">물류통계정보학과</option>\r\n");
      out.write("\t\t\t\t  <option value=\"Industrial\">산업환경보건학과</option>\r\n");
      out.write("\t\t\t\t  <option value=\"media\">미디어디자인과</option>\r\n");
      out.write("\t\t\t\t  <option value=\"Culture_Contents\">문화콘텐츠학과</option>\r\n");
      out.write("\t\t\t\t<option value=\"dance\">무용학과</option>\r\n");
      out.write("\t\t\t\t<option value=\"Cultural_Heritage\">문화재학과</option>\r\n");
      out.write("\t\t\t\t<option value=\"picture\">회화학과</option>\r\n");
      out.write("\t\t\t\t<option value=\"Korean_music\">연극학과</option>\r\n");
      out.write("\t\t\t\t<option value=\"applied_music\">실용음악과</option>\r\n");
      out.write("\t\t\t\t<option value=\"Movie\">영화영상학과</option>\r\n");
      out.write("\t\t\t\t<option value=\"Management\">경영학과</option>\r\n");
      out.write("\t\t\t\t<option value=\"police\">경찰행정학과</option>\r\n");
      out.write("\t\t\t\t<option value=\"China\">중국학과</option>\r\n");
      out.write("\t\t\t\t<option value=\"Management_info\">경영정보학과</option>\r\n");
      out.write("\t\t\t\t<option value=\"English\">영어과</option>\t\t\r\n");
      out.write("\t\t\t\t  <option value=\"Culture_tour\">문화관광학과</option>\r\n");
      out.write("\t\t\t\t  <option value=\"Food_nutrition\">식품영양학과</option>\r\n");
      out.write("\t\t\t\t  <option value=\"Physical_therapy\">물리치료학과</option>\r\n");
      out.write("\t\t\t\t  <option value=\"Social_welfare\">사회복지학과</option>\r\n");
      out.write("\t\t\t\t  <option value=\"Sports_leisure\">스포츠레저학과</option>\r\n");
      out.write("\t\t\t\t  <option value=\"Golf\">골프학과</option>\r\n");
      out.write("\t\t\t\t  <option value=\"Physical\">체육학과</option>\r\n");
      out.write("\t\t\t\t  <option value=\"Special_sports\">특수체육교육학과</option>\r\n");
      out.write("\t\t\t\t  <option value=\"judo\">유도학과</option>\r\n");
      out.write("\t\t\t\t   <option value=\"judo_game\">유도경기지도학과</option>\r\n");
      out.write("\t\t\t\t  <option value=\"Taekwondo\">태권도학과</option>\r\n");
      out.write("\t\t\t\t  <option value=\"Taekwondo_game\">태권도경기지도학과</option>\r\n");
      out.write("\t\t\t\t  <option value=\"combative\">격기지도학과</option>\r\n");
      out.write("\t\t\t\t  <option value=\"Guard\">경호학과</option>\r\n");
      out.write("\t\t\t\t  <option value=\"Oriental\">동양무예학과</option>\r\n");
      out.write("\t\t\t\t  <option value=\"military_affairs\">군사학과</option>\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\r\n");
      out.write("                </select>\r\n");
      out.write("                <div class=\"invalid-feedback\" style=\"width: 100%;\">\r\n");
      out.write("                  학과선택해주세요\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("              <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                <label for=\"country\">직위</label>\r\n");
      out.write("                <select class=\"custom-select d-block w-100\" id=\"role\" name=\"role\" >\r\n");
      out.write("                  <option value=\"\">Choose...</option>\r\n");
      out.write("                  <option value=\"boss\">팀장</option>\r\n");
      out.write("\t\t\t\t  <option value=\"member\" selected=\"selected\">팀원</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                <div class=\"invalid-feedback\">\r\n");
      out.write("                  Please select a valid country.\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("             \r\n");
      out.write("              </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6 mb-3\">\r\n");
      out.write("              <label for=\"address\">전화번호</label>\r\n");
      out.write("              <input type=\"text\" class=\"form-control\" id=\"phone\" placeholder=\"010********\" onkeydown='return onlyNumber(event)' onkeyup='removeChar(event)' name=\"phone\" required>\r\n");
      out.write("              <div class=\"invalid-feedback\">\r\n");
      out.write("                \t전화번호를 입력해주세요\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t            <div class=\"col-md-6 mb-3\">\r\n");
      out.write("              <label for=\"email\">Email</label>\r\n");
      out.write("              <input type=\"email\" class=\"form-control\" id=\"email\" placeholder=\"you@example.com\" name=\"email\"required>\r\n");
      out.write("                   <div class=\"invalid-feedback\" style=\"width: 100%;\">\r\n");
      out.write("                  이메일을 입력해주세요\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("            </div>  \r\n");
      out.write("         \r\n");
      out.write("            <hr class=\"mb-4\">\r\n");
      out.write("            <input class=\"btn btn-outline-info btn-lg btn-block\" type=\"submit\" value=\"회원가입\"/>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core JavaScript\r\n");
      out.write("    ================================================== -->\r\n");
      out.write("    <!-- Placed at the end of the document so the pages load faster -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script>window.jQuery || document.write('<script src=\"./resource/js/jquery-slim.min.js\"><\\/script>')</script>\r\n");
      out.write("    <script src=\"./resource/js/vendor/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"./resource/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"./resource/js/vendor/holder.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("      // Example starter JavaScript for disabling form submissions if there are invalid fields\r\n");
      out.write("      (function() {\r\n");
      out.write("        'use strict';\r\n");
      out.write("\r\n");
      out.write("        window.addEventListener('load', function() {\r\n");
      out.write("          // Fetch all the forms we want to apply custom Bootstrap validation styles to\r\n");
      out.write("          var forms = document.getElementsByClassName('needs-validation');\r\n");
      out.write("\r\n");
      out.write("          // Loop over them and prevent submission\r\n");
      out.write("          var validation = Array.prototype.filter.call(forms, function(form) {\r\n");
      out.write("            form.addEventListener('submit', function(event) {\r\n");
      out.write("              if (form.checkValidity() === false) {\r\n");
      out.write("                event.preventDefault();\r\n");
      out.write("                event.stopPropagation();\r\n");
      out.write("              }\r\n");
      out.write("              form.classList.add('was-validated');\r\n");
      out.write("            }, false);\r\n");
      out.write("          });\r\n");
      out.write("        }, false);\r\n");
      out.write("      })();\r\n");
      out.write("    </script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
